### PR TITLE
Fixes for out of tree build

### PR DESCRIPTION
**Pull request by ifranzki**
Fixes https://github.com/opencryptoki/opencryptoki/issues/636 from @mhartmay and another bug with the parser generation in out of tree builds.

### CODE REVIEW

**Comment by jschmidb** [comment]
Small typo in commit msg for "Create target directory for generated sources": 
For out-of-tree builds, the target directory usr/lib/config may not exits   <- exist

**Review by juergenchrist — APPROVED** [review]

**Comment by ifranzki** [comment]
Travis failures don't seem to be related. Looks like timeouts in the environment....

**Comment by ifranzki** [comment]
> Small typo in commit msg for "Create target directory for generated sources": For out-of-tree builds, the target directory usr/lib/config may not exits <- exist

fixed.

**Comment by mhartmay** [comment]
Tested-by: Marc Hartmayer <marc@linux.ibm.com>

Thanks.

**Comment by ifranzki** [comment]
Added Marcs "Tested by" to commits.

**Pull request merged**
