### PR TITLE
A couple of pkcstok_migrate fixes

### PR DESCRIPTION
**Pull request by ifranzki**
Fix some problems of pkcstok_migrate to maybe get if finally clean for the new OCK release....

### CODE REVIEW

**Review by juergenchrist — APPROVED** [review]
lgtm

**Comment by jschmidb** [comment]
lgtm .... one minor typo in commit msg: An token data store with zero objects -> A token data store

**Comment by jschmidb** [comment]
And another typo in commit  pkcstok_migrate: Better preserve comments during config file migration
Preserver the original comments during migration -> Preserve the original ...

**Review by jschmidb — APPROVED** [review]

**Comment by ifranzki** [comment]
Fixed the typos in the commit message found by @jschmidb. No code change, just commit message changes.

**Review by p-steuer — APPROVED** [review]

**Pull request merged**
