### PR TITLE
Fix attribute-array flatten and unflatten

### PR DESCRIPTION
**Pull request by ifranzki**
Some ULONG attributes are always stored as 32 bit ULONG, while others are stored in the length that CK_ULONG is on the systems architecture. I.e. on a 64 bit system a CK_ULONG is 64 bit in size, while on a 32 bit system it is 32 bit in size.

The same logic must also be used when unflattening attribute-array elements, when an element is such an attribute that is always stored as 32 bit ULONG.

Also fix an error when flattening an attribute-array element.

### CODE REVIEW

**Review by juergenchrist — APPROVED** [review]

**Comment by p-steuer** [comment]
Is this change backward compatible ?

**Comment by ifranzki** [comment]
The code that introduced the bug was added after 3.15.1, so it is not included in any distro so far.  
The bug caused that attribute-array attributes with > 0 elements were always stored incorrectly, so this did never really work since the code was introduced anyway.

**Comment by ifranzki** [comment]
I added one more commit to enhance a testcase to test attribute-array attributes.

**Review by p-steuer — APPROVED** [review]

**Comment by juergenchrist** [comment]
Please merge this PR soon.  It fixes some of our daily CI errors...

**Review by p-steuer — APPROVED** [review]

**Pull request merged**
