### PR TITLE
Fixes for ci

### PR DESCRIPTION
**Pull request by holger-dengler**
The PR #565 unfortunately introduced a ci-breakage. This PR contains the required fixes to make ci runable again.

### CODE REVIEW

**Review by juergenchrist — APPROVED** [review]
lgtm

**Review by ifranzki — APPROVED** [review]
lgtm

**Comment by jschmidb** [comment]
lgtm.
Just one typo in commit msg:
Makefile.am: fix ci-installcheck target
... introduced the usage og bash-commands   <- of

**Review by jschmidb — APPROVED** [review]

**Comment by holger-dengler** [comment]
I'll fix the typo and push it again.

**Comment by holger-dengler** [comment]
Here is the change.

```
$ git range-diff origin/master  6e419cc 897f369
1:  ef260757 ! 1:  80e483fc Makefile.am: fix ci-installcheck target
    @@ Commit message
         Makefile.am: fix ci-installcheck target

         Commit 0ff979160011 ("testcases: misc: add pkcsconf URI tests") introduced
    -    the usage og bash-commands in ci-installcheck target. Replace these bash
    +    the usage of bash-commands in ci-installcheck target. Replace these bash
         commands and call both tests in the same shell context.

         Signed-off-by: Holger Dengler <dengler@linux.ibm.com>
2:  6e419ccd = 2:  897f369c testcases: misc: fix missing testfile name
```

**Pull request merged**
