### PR TITLE
Cleanup incomplete DH implementation for CCA, ICA, TPM and ICSF tokens

### PR DESCRIPTION
**Pull request by ifranzki**
This fixes https://github.com/opencryptoki/opencryptoki/issues/30

The NODH define as such is kept so far, since it controls if DH specific common code parts are included. This is similar to the NODSA, NOAES defines.

### CODE REVIEW

**Comment by p-steuer** [comment]
Did you check if ./configure CFLAGS="-DNODH -DNODSA -DNOAES" build is working ?

**Comment by ifranzki** [comment]
Hm, no this fails... let me look into this.

**Comment by p-steuer** [comment]
This is why i suggested to remove disabling algorithms at compile time completely. openssl already has such defines on which you technically depend (e.g. your openssl rsa code has an #ifndef OPENSSL_NO_RSA). Introducing a second set of such compiler time options intruduces a lot of complexity (e.g. #if !defined(OPENSSL_NO_RSA) && !defined(NORSA) ) ..

**Comment by ifranzki** [comment]
I have fixed the compile errors with ./configure CFLAGS="-DNODH -DNODSA -DNOAES"
We can still decide to remove NOxxx defines completely.... Not sure what the original rational was to introduce these defines.

**Pull request merged**
