### PR TITLE
[pkcsconf] Add missing CKM_IBM_ATTRIBUTEBOUND_WRAP

### PR DESCRIPTION
**Pull request by juergenchrist**
Oversight when adding support for attribute bound wrapping:

Mechanism #50
        Mechanism: 0x80020004
        Key Size: 0-4096
        Flags: 0x60000 (CKF_WRAP|CKF_UNWRAP)

Make CKM_IBM_ATTRIBUTEBOUND_WRAP known to pkcsconf

Signed-off-by: Juergen Christ <jchrist@linux.ibm.com>

### CODE REVIEW

**Review by ifranzki — APPROVED** [review]
I don't know why, but in usr/sbin/pkcsslotd/err,c there is also a list of mechanism. CKM_IBM_ATTRIBUTEBOUND_WRAP is missing there, too. However, I don't think that list is used for anything....

**Comment by juergenchrist** [comment]
> in usr/sbin/pkcsslotd/err,c there is also a list of mechanisms

Added it there too.

**Comment by ifranzki** [comment]
Stange, why does this PR not trigger a travis build?

**Comment by p-steuer** [comment]
Happens sometimes. Just try to close & reopen the PR

**Review by p-steuer — APPROVED** [review]

**Pull request merged**
