### PR TITLE
common: Fix compile error/warning when compiled with GCC 14

### PR DESCRIPTION
**Pull request by ifranzki**
usr/lib/common/mech_openssl.c:2425:51:
   error: passing argument 5 of 'EVP_PKEY_get_octet_string_param' from
          incompatible pointer type

Change ecpoint_len to type size_t instead of CK_ULONG to match the expected type used by EVP_PKEY_get_octet_string_param(). Also, for the further use of that variable it is OK to use size_t.

### CODE REVIEW

**Comment by ifranzki** [comment]
@sharkcz OK, fixed several more places. 
I have added all this to the one commit, so please check again if now all places are fixed.
Unfortunately I can't reproduce myself, because `size_t` seems to be an `unsigned long int` on my systems, while in your case its a `unsigned int`.  Are you compiling on a 32 bit system?

**Comment by sharkcz** [comment]
yes, technically it is a 32-bit system, it's a 32-bit chroot/container on top of a x86_64 host

I will give it another try and let you know.

**Comment by ifranzki** [comment]
Just FYI: At some point in time we will remove support for 32 bit systems, also see https://github.com/opencryptoki/opencryptoki/issues/174

**Comment by sharkcz** [comment]
> Just FYI: At some point in time we will remove support for 32 bit systems, also see #174

ack, it is already encouraged in Fedora to remove leaf package for i686

on the other hand the warnings from a 32-bit system allow to write better/safer code

**Comment by sharkcz** [comment]
now it fails at `icsf_stdll`, please see https://kojipkgs.fedoraproject.org//work/tasks/6083/112536083/build.log

**Comment by ifranzki** [comment]
> now it fails at `icsf_stdll`, please see https://kojipkgs.fedoraproject.org//work/tasks/8858/112548858/build.log

Hmm, are you sure you applied the complete commit?  All the places that still fail have been fixed in the commit, e.g. see https://github.com/opencryptoki/opencryptoki/pull/741/commits/94d5ff15acaf8e85103825a4252ddcff3281b3f1#diff-d474f6728105facd0bb6500ab896ed1e6e8681e540e92a211b7a49565ef5d21c

**Comment by ifranzki** [comment]
Ah right, forgot to update the header.... Fixed that and some more findings shown in your log.
Give it another try please with the updated commit.

**Comment by sharkcz** [comment]
The last version looks good, no errors, just 2 formatting warnings, please see https://kojipkgs.fedoraproject.org//work/tasks/7336/112607336/build.log

**Comment by ifranzki** [comment]
Fixed those 2 warnings as well.

**Comment by sharkcz** [comment]
Awesome, thanks a lot, not a single warning on any platform, see https://koji.fedoraproject.org/koji/taskinfo?taskID=112610096

**Review by sharkcz — APPROVED** [review]
LGTM

**Pull request merged**
