### PR TITLE
CI: Perform cleanup of left over EP11 sessions

### PR DESCRIPTION
**Pull request by ifranzki**
Allow to cleanup left over EP11 sessions for CI runs via 'make ci-cleanup'. This is to be called by the CI after 'make ci-installcheck', and before pkcsslotd is terminated.

### CODE REVIEW

**Review by juergenchrist — APPROVED** [review]
lgtm

**Comment by ifranzki** [comment]
Well, I guess it still needs some rework:
It should use the PIN ('01234567') that was set up by init_token.sh also for the ci-cleanup step, or, if PKCS11_USER_PIN is set, use that one.

init_vhsm.exp also should use the pin fromPKCS11_USER_PIN  if it is set, I guess.

**Comment by ifranzki** [comment]
> It should use the PIN ('01234567') that was set up by init_token.sh also for the ci-cleanup step, or, if PKCS11_USER_PIN is set, use that one.

Well, that's alrady done by:
`PKCS11_USER_PIN ?= 01234567`

> init_vhsm.exp also should use the pin fromPKCS11_USER_PIN if it is set, I guess.

Will add tis in a second commit, to pass PKCS11_USER_PIN and PKCS11_VHSM_PIN to init_vhsm.exp

**Comment by juergenchrist** [comment]
> Will add tis in a second commit, to pass PKCS11_USER_PIN and PKCS11_VHSM_PIN to init_vhsm.exp

Maybe while you are at it, you could pass PKCS11_USER_PIN also to init_token.sh and use it there?  It seems to have _all_ values hardcoded...

**Review by juergenchrist — APPROVED** [review]

**Review by p-steuer — APPROVED** [review]

**Pull request merged**
