### PR TITLE
COMMON: Retry RSA key gen if it fails with OpenSSL 3.0

### PR DESCRIPTION
**Pull request by ifranzki**
In OpenSSL 3.0 the RSA key gen algorithm has been changed and can now fail to generate a key. Retry up to 10 times in such a case.

### CODE REVIEW

**Comment by ifranzki** [comment]
@jschmidb ping ?

**Review by jschmidb — APPROVED** [review]
lgtm. Same as for libica.

**Comment by ifranzki** [comment]
Just added a retry for the ICA token as well. Although the libica also has this retry already, we might run with an distro built libica that does not have the retry logic yet. So do the retry in the ICA token as well.

**Review by jschmidb — APPROVED** [review]
perfect

**Pull request merged**
