### PR TITLE
Makefile and configure cleanups

### PR DESCRIPTION
**Pull request by ifranzki**

### CODE REVIEW

**Comment by jschmidb** [comment]
From review together with Vishnu
Typo in commit msg: 
configure: Remove superflous --with-zcrypt configure option    <- superfluous

**Review by jschmidb — APPROVED** [review]
ok

**Review by vkanjur — APPROVED** [review]
approved

**Review by jschmidb — APPROVED** [review]
ok

**Comment by ifranzki** [comment]
Fixed typo in commit msg.

**Pull request merged**
